export const SAVE_REQUEST_INITIATED = "SAVE_REQUEST_INITIATED";
export const SAVE_REQUEST_SUCCESS = "SAVE_REQUEST_SUCCESS";
export const SAVE_REQUEST_ERROR = "SAVE_REQUEST_ERROR";

export const DELETE_REQUEST_INITIATED = "DELETE_REQUEST_INITIATED";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_ERROR = "DELETE_REQUEST_ERROR";

export const GET_REQUEST_LIST_INITIATED = "GET_REQUEST_LIST_INITIATED";
export const GET_REQUEST_LIST_SUCCESS = "GET_REQUEST_LIST_SUCCESS";
export const GET_REQUEST_LIST_ERROR = "GET_REQUEST_LIST_ERROR";

export const GET_REQUEST_DETAIL_INITIATED = "GET_REQUEST_DETAIL_INITIATED";
export const GET_REQUEST_DETAIL_SUCCESS = "GET_REQUEST_DETAIL_SUCCESS";
export const GET_REQUEST_DETAIL_ERROR = "GET_REQUEST_DETAIL_ERROR";

export const COMPLETE_REQUEST_INITIATED = "COMPLETE_REQUEST_INITIATED";
export const COMPLETE_REQUEST_SUCCESS = "COMPLETE_REQUEST_SUCCESS";
export const COMPLETE_REQUEST_ERROR = "COMPLETE_REQUEST_ERROR";

export const INITIATED_REQUEST_INITIATED = "INITIATED_REQUEST_INITIATED";
export const INITIATED_REQUEST_SUCCESS = "INITIATED_REQUEST_SUCCESS";
export const INITIATED_REQUEST_ERROR = "INITIATED_REQUEST_ERROR";
