export const ADD_FLOOR_INITIATED = "ADD_FLOOR_INITIATED";
export const ADD_FLOOR_SUCCESS = "ADD_FLOOR_SUCCESS";
export const ADD_FLOOR_ERROR = "ADD_FLOOR_ERROR";

export const GET_FLOOR_INITIATED = "GET_FLOOR_INITIATED";
export const GET_FLOOR_SUCCESS = "GET_FLOOR_SUCCESS";
export const GET_FLOOR_ERROR = "GET_FLOOR_ERROR";

export const DELETE_FLOOR_INITIATED = "DELETE_FLOOR_INITIATED";
export const DELETE_FLOOR_SUCCESS = "DELETE_FLOOR_SUCCESS";
export const DELETE_FLOOR_ERROR = "DELETE_FLOOR_ERROR";

export const GET_FLOOR_DETAIL_INITIATED = "  GET_FLOOR_DETAILL_INITIATED";
export const GET_FLOOR_DETAIL_SUCCESS = "  GET_FLOOR_DETAILL_SUCCESS";
export const GET_FLOOR_DETAIL_ERROR = "  GET_FLOOR_DETAILL_ERROR";

export const ENABLE_FLOOR_INITIATED = "ENABLE_FLOOR_INITIATED";
export const ENABLE_FLOOR_SUCCESS = "ENABLE_FLOOR_SUCCESS";
export const ENABLE_FLOOR_ERROR = "ENABLE_FLOOR_ERROR";

export const GET_FLOOR_DROP_INITIATED = "GET_FLOOR_DROP_INITIATED";
export const GET_FLOOR_DROP_SUCCESS = "GET_FLOOR_DROP_SUCCESS";
export const GET_FLOOR_DROP_ERROR = "GET_FLOOR_DROP_ERROR";
