export const TOGGLE_CHECK_PASSWORD = "TOGGLE_CHECK_PASSWORD";

export const LOGIN_INITIATED = "LOGIN_INITIATED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CHANGE_PASSWORD_INITIATED = "CHANGE_PASSWORD_INITIATED";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
