export const UPDATE_PORTER_PROFILE_INITIATED =
  " UPDATE_PORTER_PROFILE_INITIATED";
export const UPDATE_PORTER_PROFILE_SUCCESS = " UPDATE_PORTER_PROFILE_SUCCESS";
export const UPDATE_PORTER_PROFILE_ERROR = "  UPDATE_PORTER_PROFILE_ERROR";

export const GET_REQUEST_LIST_INITIATED = " GET_REQUEST_LIST_INITIATED";
export const GET_REQUEST_LIST_SUCCESS = "GET_REQUEST_LIST_SUCCESS";
export const GET_REQUEST_LIST_ERROR = "GET_REQUEST_LIST_ERROR";

export const SET_REQUEST_ACCEPTANCE_INITIATED =
  "SET_REQUEST_ACCEPTANCE_INITIATED";
export const SET_REQUEST_ACCEPTANCE_SUCCESS = "SET_REQUEST_ACCEPTANCE_SUCCESS";
export const SET_REQUEST_ACCEPTANCE_ERROR = "SET_REQUEST_ACCEPTANCE_ERROR";

export const GET_ACCEPTED_REQUEST_INITIATED = "GET_ACCEPTED_REQUEST_INITIATED";
export const GET_ACCEPTED_REQUEST_SUCCESS = "GET_ACCEPTED_REQUEST_SUCCESS";
export const GET_ACCEPTED_REQUEST_ERROR = "GET_ACCEPTED_REQUEST_ERROR";

export const GET_REJECTED_REQUEST_INITIATED = "GET_REJECTED_REQUEST_INITIATED";
export const GET_REJECTED_REQUEST_SUCCESS = "GET_REJECTED_REQUEST_SUCCESS";
export const GET_REJECTED_REQUEST_ERROR = "GET_REJECTED_REQUEST_ERROR";

export const SET_START_JOB_INITIATED = " SET_START_JOB_INITIATED";
export const SET_START_JOB_SUCCESS = " SET_START_JOB_SUCCESS";
export const SET_START_JOB_ERROR = " SET_START_JOB_ERROR";

export const SET_FINISH_JOB_INITIATED = "SET_FINISH_JOB_INITIATED";
export const SET_FINISH_JOB_SUCCESS = "SET_FINISH_JOB_SUCCESS";
export const SET_FINISH_JOB_ERROR = "SET_FINISH_JOB_ERROR";

export const GET_STATUS_INITIATED = " GET_STATUS_INITIATED";
export const GET_STATUS_SUCCESS = " GET_STATUS_SUCCESS";
export const GET_STATUS_ERROR = " GET_STATUS_ERROR";

export const GET_UPDATE_STATUS_INITIATED = "GET_UPDATE_STATUS_INITIATED";
export const GET_UPDATE_STATUS_SUCCESS = " GET_UPDATE_STATUS_SUCCESS";
export const GET_UPDATE_STATUS_ERROR = " GET_UPDATE_STATUS_ERROR";

export const GET_PORTER_PROFILE_INITIATED = "GET_PORTER_PROFILE_INITIATED";
export const GET_PORTER_PROFILE_SUCCESS = "GET_PORTER_PROFILE_SUCCESS";
export const GET_PORTER_PROFILE_ERROR = " GET_PORTER_PROFILE_ERROR";
