export const GET_REQUEST_TYPE_INITIATED = "GET_REQUEST_TYPE_INITIATED";
export const GET_REQUEST_TYPE_SUCCESS = "GET_REQUEST_TYPE_SUCCESS";
export const GET_REQUEST_TYPE_ERROR = "GET_REQUEST_TYPE_ERROR";
