export const ADD_LOCATION_INITIATED = "ADD_LOCATION_INITIATED";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_ERROR = "ADD_LOCATION_ERROR";

export const GET_LOCATION_INITIATED = "GET_LOCATION_INITIATED";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";

export const DELETE_LOCATION_INITIATED = "DELETE_LOCATION_INITIATED";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_ERROR = "DELETE_LOCATION_ERROR";

export const GET_LOCATION_DETAIL_INITIATED = "  GET_LOCATION_DETAILL_INITIATED";
export const GET_LOCATION_DETAIL_SUCCESS = "  GET_LOCATION_DETAILL_SUCCESS";
export const GET_LOCATION_DETAIL_ERROR = "  GET_LOCATION_DETAILL_ERROR";

export const ENABLE_LOCATION_INITIATED = "ENABLE_LOCATION_INITIATED";
export const ENABLE_LOCATION_SUCCESS = "ENABLE_LOCATION_SUCCESS";
export const ENABLE_LOCATION_ERROR = "ENABLE_LOCATION_ERROR";

export const GET_LOCATION_DROP_INITIATED = "GET_LOCATION_DROP_INITIATED";
export const GET_LOCATION_DROP_SUCCESS = "GET_LOCATION_DROP_SUCCESS";
export const GET_LOCATION_DROP_ERROR = "GET_LOCATION_DROP_ERROR";