export const GET_NOTIFICATION_INITIATED = "GET_NOTIFICATION_INITIATED";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";

export const GET_READ_NOTIFICATION_INITIATED =
  "GET_READ_NOTIFICATION_INITIATED";
export const GET_READ_NOTIFICATION_SUCCESS = "GET_READ_NOTIFICATION_SUCCESS";
export const GET_READ_NOTIFICATION_ERROR = "GET_READ_NOTIFICATION_ERROR";
