export const EMPLOYEE_REPORT_INITIATED = "EMPLOYEE_REPORT_INITIATED";
export const EMPLOYEE_REPORT_SUCCESS = "EMPLOYEE_REPORT_SUCCESS";
export const EMPLOYEE_REPORT_ERROR = "EMPLOYEE_REPORT_ERROR";

export const PORTER_REPORT_INITIATED = "PORTER_REPORT_INITIATED";
export const PORTER_REPORT_SUCCESS = "PORTER_REPORT_SUCCESS";
export const PORTER_REPORT_ERROR = "PORTER_REPORT_ERROR";

export const JOB_REPORT_INITIATED = "JOB_REPORT_INITIATED";
export const JOB_REPORT_SUCCESS = "JOB_REPORT_SUCCESS";
export const JOB_REPORT_ERROR = "JOB_REPORT_ERROR";

export const FLOOR_REPORT_INITIATED = "FLOOR_REPORT_INITIATED";
export const FLOOR_REPORT_SUCCESS = "FLOOR_REPORT_SUCCESS";
export const FLOOR_REPORT_ERROR = "FLOOR_REPORT_ERROR";

export const LOCATION_REPORT_INITIATED = "LOCATION_REPORT_INITIATED";
export const LOCATION_REPORT_SUCCESS = "LOCATION_REPORT_SUCCESS";
export const LOCATION_REPORT_ERROR = "LOCATION_REPORT_ERROR";

export const GET_DASHBOARD_DETAIL_INITIATED = "GET_DASHBOARD_DETAIL_INITIATED";
export const GET_DASHBOARD_DETAIL_SUCCESS = "GET_DASHBOARD_DETAIL_SUCCESS";
export const GET_DASHBOARD_DETAIL_ERROR = "GET_DASHBOARD_DETAIL_ERROR";

export const GET_PIE_CHART_INITIATED = "GET_PIE_CHART_INITIATED";
export const GET_PIE_CHART_SUCCESS = "GET_PIE_CHART_SUCCESS";
export const GET_PIE_CHART_ERROR = "GET_PIE_CHART_ERROR";
