export const ADD_PORTER_INITIATED = "ADD_PORTER_INITIATED";
export const ADD_PORTER_SUCCESS = "ADD_PORTER_SUCCESS";
export const ADD_PORTER_ERROR = "ADD_PORTER_ERROR";

export const GET_PORTER_INITIATED = "GET_PORTER_INITIATED";
export const GET_PORTER_SUCCESS = "GET_PORTER_SUCCESS";
export const GET_PORTER_ERROR = "GET_PORTER_ERROR";

export const DELETE_PORTER_INITIATED = "DELETE_PORTER_INITIATED";
export const DELETE_PORTER_SUCCESS = "DELETE_PORTER_SUCCESS";
export const DELETE_PORTER_ERROR = "DELETE_PORTER_ERROR";

export const GET_PORTER_DETAIL_INITIATED = "GET_PORTER_DETAIL_INITIATED";
export const GET_PORTER_DETAIL_SUCCESS = "GET_PORTER_DETAIL_SUCCESS";
export const GET_PORTER_DETAIL_ERROR = "GET_PORTER_DETAIL_ERROR";

export const ENABLE_PORTER_INITIATED = "ENABLE_PORTER_INITIATED";
export const ENABLE_PORTER_SUCCESS = "ENABLE_PORTER_SUCCESS";
export const ENABLE_PORTER_ERROR = "ENABLE_PORTER_ERROR";
