export const ADD_EMPLOYEE_INITIATED = "ADD_EMPLOYEE_INITIATED";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";

export const GET_EMPLOYEE_INITIATED = "GET_EMPLOYEE_INITIATED";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYEE_ERROR";

export const DELETE_EMPLOYEE_INITIATED = "DELETE_EMPLOYEE_INITIATED";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR";

export const  GET_EMPLOYEE_DETAIL_INITIATED = "  GET_EMPLOYEE_DETAILL_INITIATED";
export const  GET_EMPLOYEE_DETAIL_SUCCESS = "  GET_EMPLOYEE_DETAILL_SUCCESS";
export const  GET_EMPLOYEE_DETAIL_ERROR = "  GET_EMPLOYEE_DETAILL_ERROR";

export const ENABLE_EMPLOYEE_INITIATED = "ENABLE_EMPLOYEE_INITIATED";
export const ENABLE_EMPLOYEE_SUCCESS = "ENABLE_EMPLOYEE_SUCCESS";
export const ENABLE_EMPLOYEE_ERROR = "ENABLE_EMPLOYEE_ERROR";

export const GET_EMPLOYEE_LOCATION_INITIATED = "GET_EMPLOYEE_LOCATION_INITIATED";
export const GET_EMPLOYEE_LOCATION_SUCCESS = "GET_EMPLOYEE_LOCATION_SUCCESS";
export const GET_EMPLOYEE_LOCATION_ERROR = "GET_EMPLOYEE_LOCATION_ERROR";
