export const IMPORT_EMPLOYEE_INITIATED = "IMPORT_EMPLOYEE_INITIATED";
export const IMPORT_EMPLOYEE_SUCCESS = "IMPORT_EMPLOYEE_SUCCESS";
export const IMPORT_EMPLOYEE_ERROR = "IMPORT_EMPLOYEE_ERROR";

export const IMPORT_PORTER_INITIATED = "IMPORT_PORTER_INITIATED";
export const IMPORT_PORTER_SUCCESS = "IMPORT_PORTER_SUCCESS";
export const IMPORT_PORTER_ERROR = "IMPORT_PORTER_ERROR";
