const FormValidation = {
  nameMin: "Please enter at least 2 alphabet characters",
  nameValid: "Please enter alphabet character",
  usernameMin: "Please enter at least 3 characters.",
  userValid: "Please enter at least one alphabet character",
  passwordMin: "Please enter at least 2 characters",
  // "Please enter at least 8 characters, One Uppercase, One Lowercase, One Number and One Special Case Character",
  passwordMax: "Please not enter more than 25 characters.",
  emailInvalid: "Please enter valid email address.",
  mobileInvalid: "Please enter valid mobile number.",
  sameLoc: "Can't use same pickup & destination location again.",
  RepatePWD:
    "Both 'New Password' & 'Conform New Password' need to be the same.",
  passwordInvalid:
    "Must Contain One Uppercase, One Lowercase, One Number and One Special Case Character",
};
const ButtonConstant = {
  cancel: "Cancel",
  save: "Save",
  edit: "Edit",
  submit: "Submit",
  delete: "Delete",
  download: "Download",
  Upload: "Upload",
  add: "Add",
  update: "Update",
  next: "Next",
};
const RemoveConst = {
  yes: "Yes",
  danger: "danger",
  no: "No ",
  header: "Delete ",
  que: " ?",
  deleteMessage: "Are you sure you want to remove ",
  logMessage: "Are you sure you want to logout?",
  dropText: "Drop image here or click to browse file here",
};
const PwdMatch =
  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$*#?&^_()[\]])[A-Za-z\d@$*#?&^_()[\]]{8,}$/;
const UserMatch = /^((?=.*[A-Za-z]){1}).*$/;
const PageConst = {
  dashHead: "Hello,Admin",
  empMast: "Employee Master",
  addEmp: "Add New Employee",
  editEmp: "Edit Employee",
  emp: "Employee",
  empnm: "Emp Name",
  fnm: " First Name",
  lnm: "Last Name",
  email: "Email",
  emid: "Email ID",
  mobile: "Mobile No.",
  floor: "Floor",
  loc: "Location",
  uname: "UserName",
  pwd: "Password",
  desig: "Designation",
  address: "Address",
  addPort: "Add New Porter",
  name: "Name",
  addReq: "Add New Request",
  editReq: "Edit Request",
  req: "Request",
  pick: "Pickup",
  dest: "Destination",
  port: "Porters",
  por: "Porter",
  pri: "Priority",
  rmark: "Remark*",
  floorMast: "Floor / Location Master",
  porMast: "Porter Master",
  editpor: "Edit Porter",
  rep: "Reports",
  hi: "Hi, ",
  admin: "Admin",
  status: "Status",
  rem: "Remarks",
  comp: "Completed",
  active: "Active",
  disable: "Inactive",
  changePwd: "Change Password",
  logout: "Log Out",
  dash: "Dashboard",
  oldpwd: "Old Password",
  newpwd: "New Password",
  conpwd: "Conform New Password",
  editPhoto: "Edit Photo",
  dropText: "Drop image here or click to browse file here",
  fill: "Fill out the form below to ",
  log: "login",
  to: "To",
  colon: ":",
  star: "*",
  fp: "Forgot Password?",
  pa: "Porter App",
  Login: "Login",
  adiBul: "Add in Bulk",
  dowExTamp: "Download Excel Teamplate",
  upExTamp: "Upload Excel Teamplate",
  propic: "profile photo",
  print: "Print",
  pdf: "PDF",
  excel: "Excel",
  csv: "CSV",
  expoas: "Export as",
  sr: "#",
  repoId: "Report ID",
  fd: "From Date",
  td: "To Date",
  search: "Search...",
  reqby: "Requested by",
  st:"Start Time to End Time",
  tat:"TAT",
  pickloc: "Pickup Location",
  destLoc: "Destination Location",
  noPor: "No of Porters",
  jobid: "Job ID",
  frmLoc: "From Location",
  toLoc: "To Location",
  starttm: "Start Time",
  endtm: "End Time",
  tat: "TAT",
  avail: "Availability",
  ava: "Available",
  rest: "Rest",
  tjob: "Total Jobs",
  tnoj: "Total No. of Job : ",
  at: "Average time : ",
  accby: "Accepted By",
  date: "Date",
  profile: "Profile",
  cj: "Current Job",
  jc: "Job Finished",
  jr: "Job Rejected",
  reject: "Reject",
  accept: "Accept",
  from: "From",
  startj: "Start Job",
  endj: "End Job",
  ts: "Time spent",
  av: "Active Porters",
  ar: "Active Jobs",
  fr: "Finished Jobs",
  map: "Most Active Porter",
  notif: "Notifications",
  no: "No",
  va: "View All",
  add: "Add ",
  hor: "Hours",
  min: "Minutes",
  sec: "Seconds",
  zero: "00",
};
export {
  FormValidation,
  ButtonConstant,
  RemoveConst,
  PageConst,
  PwdMatch,
  UserMatch,
};
